Repository HYF-Class21/agile-development-group4-loruki-rebuild, pull requests merged in 2023-04, with the labels that each got.

#3 added communication plan
  planning/communication.md
Labels: md

#8 Added userpersona
  planning/user-personas.md
Labels: md

#13 Added project definition
  README.md
Labels: md

#20 Add CouldHave and ShouldHave to Backlog
  planning/backlog.md
Labels: md

#28 Add Introduction
  index.html
  planning/backlog.md
  planning/development-strategy.md
  styles/index.css
Labels: html, css

#35 Added Credit/stats
  index.html
  styles/index.css
Labels: html, css

#33 update header
  index.html
  styles/index.css
Labels: html, css

#40 Added Languages
  images/logos/clojure.png
  images/logos/csharp.png
  images/logos/go.png
  images/logos/node.png
  images/logos/php.png
  images/logos/python.png
  images/logos/ruby.png
  images/logos/scala.png
  index.html
  planning/backlog.md
  planning/development-strategy.md
  styles/index.css
Labels: html, css

#41 Added Extra Ad for the cloud Service
  images/cloud.png
  index.html
  styles/index.css
Labels: html, css

#43 Added Social Links
  index.html
  styles/index.css
Labels: html, css

#49 Constraints file after review
  planning/constraints.md
Labels: md

#47 update design file
  public/wire-frame-loruki.png
Labels: md

#51 update backlog as per the review
  planning/backlog.md
Labels: md

#53 Edit development strategy
  planning/backlog.md
  planning/development-strategy.md
Labels: bug, md

#55 Added retrospective
  planning/retrospective.md
Labels: md

#57 made some corrections at design
  images/docs.png
  images/features.png
  images/home.png
  planning/backlog.md
  planning/design.md
  planning/development-strategy.md
Labels: md

#59 fixing img bug at design
  planning/design.md
Labels: bug

#60 edited img in the design
  planning/design.md
Labels: bug, md

#62 Added Setup to README
  README.md
Labels: md
